import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/About.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import AboutCompany from "@/components/About/AboutCompany";
import Advantages from "@/components/About/Advantages";

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <NavBar />
        <AboutCompany />
        <Advantages />
        <Footer />
      </main>
    </>
  );
}