import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Contact.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import AboutCompany from "@/components/About/AboutCompany";
import Advantages from "@/components/About/Advantages";
import ContactForm from "@/components/ContactForm";
import OverlaySection from "@/components/About/Overlay";

export default function Contact() {
    return (
        <>
            <Head>
                <title>Trillium PC | Contact</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo_tab.png" />
            </Head>
            <main className={`${styles.main}`}>
                <NavBar />
                <ContactForm />
                <OverlaySection />
                <Footer />
            </main>
        </>
    );
}