import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Services.module.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import OverlaySection from "@/components/About/Overlay";
import OnSiteSupportComponent from "@/components/Services/OnsiteSupportComponent";

export default function OnSiteSupport() {
  return (
    <>
      <Head>
        <title>Trillium PC | OnSite Technical Support</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_tab.png" sizes="any" type="image/png" height="5px" width="auto"/>
      </Head>
      <main className={`${styles.main}`}>
        <NavBar />
        <OnSiteSupportComponent />
        <OverlaySection />
        <Footer />
      </main>
    </>
  );
}